---
- hosts: loadbalancer
  become: true
  tasks:
  - name: install mysql server
    package:
      name: mysql-server
      state: present
      
  - name: ensure mysql-server is running
    service: name=mysql state=started enabled=yes