---
- hosts: database
  become: true
  tasks:
  - name: install mysql server
    package:
      name: mysql-server
      state: present

  - name: ensure mysql-server is running
    service: name=mysql state=started enabled=yes

  - name: ensure mysql listens on all interfaces
    lineinfile: dest=/etc/mysql/my.cnf regexp=^bind-address line="bind-address = 0.0.0.0"
    notify: restart mysql

  - name: ensure mysql knows lb01
    lineinfile: dest=/etc/hosts regexp=^10.128.0.2 line="10.128.0.2 lb01" state=present

  - name: ensure mysql knows app01
    lineinfile: dest=/etc/hosts regexp=^10.128.0.3 line="10.128.0.3 app01" state=present

  - name: ensure mysql knows app02
    lineinfile: dest=/etc/hosts regexp=^10.128.0.5 line="10.128.0.5 app02" state=present

  handlers:
  - name: restart mysql
    service: name=mysql state=restarted
