---
- hosts: webserver
  become: true
  tasks:
  - name: install apache2
    apt: 
      name: ['apache2', 'libapache2-mod-wsgi', 'python-pip', 'python-virtualenv']
      state: present
      update_cache: yes
      
  - name: ensure apache2 is running
    service: name=apache2 state=started enabled=yes

  - name: ensure mod-wsgi enabled
    apache2_module: state=present name=wsgi
    notify: restart apache2

  handlers:
    - name: restart apache2
      service: name=apache2 state=restarted
    









