---
- name: ensure db01 knows lb01
  lineinfile: dest=/etc/hosts regexp=^10.128.0.2 line="10.128.0.2 lb01" state=present

- name: ensure db01 knows app01
  lineinfile: dest=/etc/hosts regexp=^10.128.0.3 line="10.128.0.3 app01" state=present

- name: ensure db01 knows app02
  lineinfile: dest=/etc/hosts regexp=^10.128.0.5 line="10.128.0.5 app02" state=present

- name: install mysql server
  package:
    name: mysql-server
    state: present

- name: install tools
  apt: 
    name: ['python-mysqldb']
    state: present
    update_cache: yes
      
- name: ensure mysql listens on all interfaces
  lineinfile: dest=/etc/mysql/my.cnf regexp=^bind-address line="bind-address = 0.0.0.0"
  notify: restart mysql

- name: create demo database
  mysql_db: name=demo state=present

- name: create demo user
  mysql_user: name=demo password=demo priv=demo.*:ALL host='%' state=present

- name: ensure mysql-server is running
  service: name=mysql state=started enabled=yes

