---
- hosts: loadbalancer 
  become: true
  tasks: 
  - name: verify nginx is up
    command: service nginx status

  - name: verify port 80
    wait_for: port=80 timeout=1

- hosts: webserver 
  become: true
  tasks: 
  - name: verify apache2 is up
    command: service apache2 status

  - name: verify port 80
    wait_for: port=80 timeout=1
      
- hosts: database 
  become: true
  tasks: 
  - name: verify mysql is up
    command: service mysql status

  - name: verify port 3306
    wait_for: port=3306 timeout=1
      